%% addEecologyqueries - example  script for adding an SQL query to a MAT file
% the query store currently resides in ../data/eecologyqueries.mat
%
% author: Elena Ranguelova, NLeSc
% date creation: 16.08.2013
% last modification date:
% modification details:

sql_gps_acc = strcat('select s.device_info_serial, s.date_time, a.date_time, ', ...
               ' date_part(''year''::text, s.date_time) AS year, ',...
               ' date_part(''month''::text, s.date_time) AS month, ',...
               ' date_part(''day''::text, s.date_time) AS day, ',...
               ' date_part(''hour''::text, s.date_time) AS hour, ',...
               ' date_part(''minute''::text, s.date_time) AS minute, ',...
               ' date_part(''second''::text, s.date_time) AS second, ',...
               ' s.speed, s.longitude, s.latitude, s.altitude, t.speed as tspeed, ',...
               ' a.index,(a.x_acceleration-d.x_o)/d.x_s as x_cal, ',...
               ' (a.y_acceleration-d.y_o)/d.y_s as y_cal, ',...
               ' (a.z_acceleration-d.z_o)/d.z_s as z_cal ',...
               ' FROM gps.uva_tracking_speed s ',...
               ' LEFT join gps.uva_acceleration101 a ',...  
               ' ON (s.device_info_serial = a.device_info_serial AND s.date_time = a.date_time) ',...
               ' LEFT join gps.uva_device d ',...
               ' ON a.device_info_serial = d.device_info_serial ',...
               ' LEFT join gps.get_uvagps_track_speed (%s,%s,%s) t ',...
               ' ON s.device_info_serial = t.device_info_serial and s.date_time = t.date_time ',...
               ' where s.device_info_serial =%s and ',...
               ' s.date_time >%s and s.date_time <%s and s.latitude is not null and s.userflag <> 1 ',...
               ' order by  s.date_time, a.index');
           
if ~exist('../data/eecologyqueries.mat','file')
    save('../data/eecologyqueries.mat','sql_gps_acc')
else
    save('../data/eecologyqueries.mat','sql_gps_acc','-append')
end
    